runtime: nodejs12

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'development'
  DATABASE_NAME: 'strapi'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'stspass616'
  INSTANCE_CONNECTION_NAME: 'bv-cmg:europe-west1:strapi'

beta_settings:
  cloud_sql_instances: 'bv-cmg:europe-west1:strapi'
